# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

spring:
  application:
    name: arcxapi-local
  # MONGODB (MongoProperties)
  profiles:
    active: local
  #    include: # additional configuration profile options such as swagger etc.
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:postgresql://dbpostgresql:5432/arcx?currentSchema=data
    url: jdbc:postgresql://localhost:5432/arcx?currentSchema=data
    username: postgres
    password: "Powell88"
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false


  data:
    rest:
      defaultMediaType=application/json:

# Logging
logging:
  level:
    com.app.arcx.*: debug
    org.springframework: warn



# server
server:
  servlet:
    context-path: /
  port: 7100



# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
