version: '3.1'
volumes:
  postgres-data:
services:
  app:
    container_name: app-springboot-postgresql
    image: app-springboot-postgresql
    build:
        context: . 
        dockerfile: Dockerfile-app
    ports:
      - "7100:7100"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: dbpostgresql
    image: postgres
    build:
        context: . 
        dockerfile: Dockerfile-dbpostgresql
